export class ActionTypes {
    static BEGIN_API_CALL = "BEGIN_API_CALL";
    static API_CALL_ERROR = "API_CALL_ERROR";


    static LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
    static LOAD_CUSTOMERS_PAGEDATA_SUCCESS = 'LOAD_CUSTOMERS_PAGEDATA_SUCCESS';
    static LOAD_CUSTOMER_SUCCESS = 'LOAD_CUSTOMER_SUCCESS';
    static CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
    static UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
    static NEW_CUSTOMER_SUCCESS = 'NEW_CUSTOMER_SUCCESS';
    static SET_CUSTOMER_BY_PROPERTY_SUCCESS = 'SET_CUSTOMER_BY_PROPERTY_SUCCESS';
    static SET_CUSTOMER_SUCCESS = 'SET_CUSTOMER_SUCCESS';
}
